apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-app1
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb-app1
  template:
    metadata:
      labels:
        app: bb-app1
    spec:
      containers:
      - name: bb-app1
        image: busybox
        command: ["sh", "-c", "while true; do sleep 35000; done"]