apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: argocd-apps-in-app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox2
  template:
    metadata:
      labels:
        app: busybox2
    spec:
      containers:
      - name: busybox2
        image: busybox
        command: ["sh", "-c", "while true; do sleep 100000; done"]