apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-app2
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb-app2
  template:
    metadata:
      labels:
        app: bb-app2
    spec:
      containers:
      - name: bb-app2
        image: busybox
        command: ["sh", "-c", "while true; do sleep 100000; done"]