apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rootapp
  namespace: argocd
  labels:
    name: rootapp
spec:
  project:  apps-in-app-project
  source:
    repoURL: https://github.com/Inx51/ArgoCDAppsInAppRoot
    path: apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
