apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
  labels:
    name: app2
spec:
  project: argocd-apps-in-app-demo
  source:
    repoURL: https://github.com/Inx51/ArgoCDAppsInAppRoot.git
    targetRevision: HEAD
    path: /app2
  destination:
    namespace: argocd