apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: x-app2
  namespace: argocd
  labels:
    name: x-app2
spec:
  project: apps-in-app-project
  source:
    repoURL: https://github.com/Inx51/ArgoCDAppsInAppRoot.git
    targetRevision: HEAD
    path: app2
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd